### ISSUE TITLE
🐛 [Bug report]: Filter plays including tag is making no impact

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#472] opened 2022-08-09 08:52 UTC
If we filter a play by tags it works but if we filter the plays with tags with a combination of other criteria, the tag selection is of no use as it never impact the criteria.

[Screencast from 09-08-22 02:15:36 PM IST.webm](https://user-images.githubusercontent.com/63530626/183607286-8ec960f3-ff90-4985-ad99-0ae83213bf7f.webm)

**Comment by dangvu0502** [comment] 2022-08-18 15:12
Hello
Is this still available for contribution?
I'd love to work on it

**Comment by atapas** [comment] 2022-08-18 15:14
> Hello
> Is this still available for contribution?
> I'd love to work on it

Yes plz

**Comment by dangvu0502** [comment] 2022-08-22 15:53
I found this issue was caused by package "json-graphql-parser".

this is how i debugged
https://drive.google.com/file/d/15vVL2Tx5d-esUTAfjhlMlIyE3fBlvn-Y/view

this is how "json-graphql-parser" work
https://drive.google.com/file/d/11AKK1CLj9h4WSQqPrMfMVN4PM_cy4UV9/view

**Comment by atapas** [comment] 2022-08-22 15:55
> I found this issue was caused by package "json-graphql-parser".
> 
> this is how i debugged https://drive.google.com/file/d/15vVL2Tx5d-esUTAfjhlMlIyE3fBlvn-Y/view
> 
> this is how "json-graphql-parser" work https://drive.google.com/file/d/11AKK1CLj9h4WSQqPrMfMVN4PM_cy4UV9/view

Can you please give access to the docs?

**Comment by dangvu0502** [comment] 2022-08-22 15:56
you mean this https://www.npmjs.com/package/json-graphql-parser ?

**Comment by Angryman18** [comment] 2022-08-22 15:57
give access

**Comment by Angryman18** [comment] 2022-08-22 16:01
i wonder how this can be an issue from a package since filtering with tags doesnt even make any graphql call.

**Comment by dangvu0502** [comment] 2022-08-22 16:08
Hmm... if you take a look at video how "json-graphql-parser" work.
You can see when you  filter the plays with tags with a combination of other criteria, it throws error.
"json-graphql-parser" can not parse obj to graphql query, i think this error affect api call.

**Comment by Angryman18** [comment] 2022-08-22 16:36
thanks for noticing it. @koustov will be up there to fix it.

**Comment by koustov** [comment] 2022-08-22 17:44
> 

I will look into it some time. BTW, this is another open-source element, https://github.com/koustov/json-graphql-parser feel free to update if you face any issue

**Comment by Angryman18** [comment] 2022-08-23 02:29
yes i checked yesterday and found the issue. its coming from processor.js and line number 101 where code is trying to push something inside an object instead of an array. i am still weak in graphql so i couldn't go further to fix it.

**Comment by atapas** [comment] 2022-08-30 09:22
Hello @dangvu0502 Thanks for the initial research. Will you take up for fixing it?

**Comment by dangvu0502** [comment] 2022-08-30 09:25
Hmm....
I'm still researching to find the solution but no progress.
I think it is better to leave for someone good at graphql

**Comment by dangvu0502** [comment] 2022-09-08 05:38
Please assign this issue to someone else as I will not be able to work on this

**Comment by Hat52** [comment] 2022-09-29 07:52
I would like to work on this issue

**Comment by supminn** [comment] 2022-10-02 15:55
> > 
> 
> I will look into it sometime. BTW, this is another open-source element, https://github.com/koustov/json-graphql-parser feel free to update if you face any issue

I have raised the issue on [json-graphql-parser](https://github.com/koustov/json-graphql-parser/issues/3)

**Comment by Hat52** [comment] 2022-10-03 15:37
So you are saying that you have already resolved the issue?

**Comment by supminn** [comment] 2022-10-03 17:37
> So you are saying that you have already resolved the issue?

Yes @Hat52 , the issue was on [json-graphql-parser](https://github.com/koustov/json-graphql-parser/issues/3). I have raised a PR with the fixes.

**Closed** 2022-10-31 08:46 UTC
Labels: bug, good first issue, hacktoberfest
