### ISSUE TITLE
[Add a Play]: TicTacToe

### ISSUE THREAD

**Issue by joshi-kaushal** [reactplay/react-play#60] opened 2022-04-19 11:18 UTC
## What's the Play about?
2 players Tic Tac Toe Game

## What ReactJS concept will be used to create this play?
useState, react basics

## Are you willing to take it up for implementation?
Yes

**Comment by SattyamSamania** [comment] 2022-12-05 15:11
Hey @atapas If the issue is still open can I work on this?

**Comment by atapas** [comment] 2022-12-05 16:03
> Hey @atapas If the issue is still open can I work on this?

Yes, you can build your own tic tac toe

**Comment by SattyamSamania** [comment] 2022-12-05 16:11
@atapas assign this issue to me and tell me which technology should I use to build that.

**Comment by SattyamSamania** [comment] 2022-12-06 03:44
@atapas can I start working on this without getting assigned?

**Closed** 2023-04-03 07:14 UTC
Labels: play-request
