### ISSUE TITLE
🐛 [Bug report]: Center text inside buttons

### ISSUE THREAD

**Issue by developer-diganta** [reactplay/react-play#536] opened 2022-09-02 14:28 UTC
**Describe the bug**
Align text inside buttons to center specially in case of smaller screens.
**To Reproduce**
1. Open the website in a smaller screen or via inspect mode(developer tools).

**Expected behavior**
Centered text inside button.

**Screenshots**
![image](https://user-images.githubusercontent.com/65999534/188171164-74cc72c5-e2cd-4a87-a02a-0cd18063b8ce.png)

If it seems valid, can I work on it?

**Comment by nirmalkc** [comment] 2022-09-03 03:17
Hi @developer-diganta, the left-aligned text inside the button is by design. For smaller resolutions, the two buttons do wrap, so it takes the full width for a larger hit area. In this case, center alignment is not good with having count for GitHub. 

Since this is not a bug, I am closing the issue.

**Closed by nirmalkc** 2022-09-03 03:17 UTC
Labels: bug
