### ISSUE TITLE
🐛 [Bug report]:  Filters - Clear all doesnt take the user back to the original state

### ISSUE THREAD

**Issue by NagarjunShroff** [reactplay/react-play#696] opened 2022-10-14 07:01 UTC
### Descrcibe the bug?

After apply all the filters, clearing them all and re-apply doesn't take the user back to the original state( it doesn't render the complete list of plays)

### Steps to reproduce the bug?

1. Add all the filters Level, Tags, Creator, and Language.
2. Click on apply to see the results.
3. Click on the filter icon and clear all filters and apply.

Another issue: Onclick of filter icon modal rerenders.

### Expected behavior

On clearing all the filters, should render a complete list of play available in the system.

### Desktop (Please provide your system information)

Browser: Chrome

### Screenshot / Screenshare

![ReactPlay - Plays](https://user-images.githubusercontent.com/37444771/195782990-897f5cf4-7d50-4f33-837f-f9f808c4c975.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Angryman18** [comment] 2022-10-14 15:58
the issue is already there #472
i guess @supminn is working on it

**Comment by supminn** [comment] 2022-11-18 12:31
This issue has been fixed. Thus, it can be marked closed.

**Comment by supminn** [comment] 2022-11-28 11:54
Hi @atapas 
Could you please close this issue? The fixes have been merged in #595

**Comment by AbhiPatel10** [comment] 2022-12-25 10:06
@atapas and @Sachin-chaurasiya  Please close this issue as this issue has been merged.

**Closed** 2022-12-25 10:42 UTC
Labels: bug
