### ISSUE TITLE
✨ [Feature request]:Convert  tailwind CSS & use  DaisyUI component 

### ISSUE THREAD

**Issue by ILhankhondaker** [reactplay/react-play#1378] opened 2023-11-02 18:16 UTC
### Is your feature request related to a problem? Please describe.

**### It's not a problem. It's a feature update.** I updated this project and added the CSS framework Tailwind CSS & daisyUI 

### Describe the solution you'd like.

Tailwind CSS is an open-source CSS framework. The main feature of this library is that, unlike other CSS frameworks like Bootstrap, it does not provide a series of predefined classes for elements such as buttons or tables. Tailwind CSS is an open-source CSS framework. The main feature of this library is that, unlike other CSS frameworks like Bootstrap, it does not provide a series of predefined classes for elements such as buttons or tables. . 

### Describe alternatives you've considered.

Tailwind CSS is best used to speed up the development process by writing less code. It comes with a design system that helps maintain consistency across various design requirements like padding, spacing, and so forth; with this, you do not have to worry about creating your design systems.

### Screenshot / Screenshare

![tailwind](https://github.com/reactplay/react-play/assets/86642752/b59b5b54-8541-4b10-95a7-0e00c95a87ea)

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue
- [X] I am in Hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment] 2023-11-19 03:13
duplicate of https://github.com/reactplay/react-play/issues/1373

**Closed by priyankarpal** 2023-11-19 03:13 UTC
Labels: duplicate, ⭐ goal: addition, 💻 aspect: code
