### ISSUE TITLE
🐛 [Bug report]: there is a "loading..." string that gets visible sometimes

### ISSUE THREAD

**Issue by NiazMorshed2007** [reactplay/react-play#1064] opened 2023-03-21 02:02 UTC
### Descrcibe the bug?

On the reactplay.io/plays page, there is a "loading..." string that gets visible sometimes after navigating between reactplay.io/ and reactplay.io/plays pages a few times.

### Steps to reproduce the bug?

1. Go to reactplay.io
2. Navigate a few times between the root and /plays page
3. Note the "loading..." under the header

### Expected behavior

The "loading..." string should not be shown and the top banner should have been visible

### Desktop (Please provide your system information)

OS: Windows 11
Browser: Chrome 
Version: 111.0.5563.64

### Screenshot / Screenshare

![Recording 2023-03-21 075328](https://user-images.githubusercontent.com/77217706/226501669-577487ff-dca4-4291-ba0a-4b83b5852059.gif)

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yeshwantthota** [comment] 2023-03-21 06:28
can i work on this issue?

**Comment by atapas** [comment] 2023-03-21 07:06
> can i work on this issue?

Assigned to you

**Comment by AkashShinde-c** [comment] 2023-03-21 08:04
Can I also try.......

**Comment by SuyashPatil-29** [comment] 2023-04-30 05:09
The issue still exists

**Comment by lalithpk** [comment] 2023-05-02 16:34
Hi, I want to contributing to this issue, can anybody please tell me is this issue still persisting

**Comment by shobhitexe** [comment] 2023-05-21 07:04
![image](https://github.com/reactplay/react-play/assets/29349136/9c9c39e7-881c-4f92-b9aa-c4bf56b2f6ff)

as i can see the issue is still there i would like to work on it

**Comment by vc8bp** [comment] 2023-05-27 05:46
hey if no one is working on this issue, I would like to work on it.

**Comment by Tahmeerpasha** [comment] 2023-05-28 14:12
If this issue is still open, I would like to work on this. Can you assign me this?

**Closed** 2023-06-14 08:15 UTC
Labels: bug, good first issue
